### ISSUE TITLE
Build error with last version

### ISSUE THREAD

**Issue by ramsestom** [fbricker/openfl-gpg#9]
Upgraded from version 1.2.2 to 1.3.0 and changed GooglePlayGames.init(FlxG.stage, false) to GooglePlayGames.init(false) but now I get that error at compillaton:

C:/HaxeToolkit/haxe/lib/openfl-gpg/1,3,0/extension/gpg/GooglePlayGames.hx:47: characters 26-36 : Cannot access private field high
C:/HaxeToolkit/haxe/lib/openfl-gpg/1,3,0/extension/gpg/GooglePlayGames.hx:47: characters 38-47 : Cannot access private field low

**Comment by fbricker** [comment]
Hi, this is due to haxe 3.2 upgrade. 
Haxe 3.2 changed the Int64 implementation, so we've upgraded the library to support that. Unfortunately, there's no back-compatibility for this. You have three options:
1) Go back to openfl-gpg version 1.2.2 (haxelib install openfl-gpg 1.2.2)
2) Upgrade haxe to the newest version.
3) Modify that file on your computer and replace this line:
```
return javaSetScore(id, score.high, score.low);
```
with this lines:
```
var low_score:Int = Int64.getLow(score);
var high_score:Int = Int64.getHigh(score);
return javaSetScore(id, high_score, low_score);
```
You can see the change here:
https://github.com/fbricker/openfl-gpg/commit/e23f1e064fde68e79f7d70ee4d2720108823d968

Thanks!

**Comment by ramsestom** [comment]
Yes I already goes back to openfl-gpg version 1.2.2 for now (haxelib set openfl-gpg 1.2.2).
I would probably try to upgrade haxe for the newest version but first, I need to ensure that it is perfectly backward compatible and would not break any other library I am using (lime, openfl, haxeflixel, firetongue and many others...) ;)
Thanks for your really quick answer.
